<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111118121403 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_inline_addressesstacked_join (admindemo_inline VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_6E57A1B99FE27C71 (admindemo_inline), INDEX IDX_6E57A1B9942C0B5 (admindemo_address), PRIMARY KEY(admindemo_inline, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_inline_addressestabular_join (admindemo_inline VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_DA866CCB9FE27C71 (admindemo_inline), INDEX IDX_DA866CCB942C0B5 (admindemo_address), PRIMARY KEY(admindemo_inline, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline_addressesstacked_join ADD CONSTRAINT FK_6E57A1B99FE27C71 FOREIGN KEY (admindemo_inline) REFERENCES admindemo_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline_addressesstacked_join ADD CONSTRAINT FK_6E57A1B9942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline_addressestabular_join ADD CONSTRAINT FK_DA866CCB9FE27C71 FOREIGN KEY (admindemo_inline) REFERENCES admindemo_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline_addressestabular_join ADD CONSTRAINT FK_DA866CCB942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline DROP FOREIGN KEY FK_C0F9FD92CB893157");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline DROP FOREIGN KEY FK_C0F9FD92D4E6F81");
		$this->addSql("DROP INDEX IDX_C0F9FD92D4E6F81 ON admindemo_domain_model_inline");
		$this->addSql("DROP INDEX IDX_C0F9FD92CB893157 ON admindemo_domain_model_inline");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD addressstacked VARCHAR(40) DEFAULT NULL, ADD addresstabular VARCHAR(40) DEFAULT NULL, DROP info, DROP address");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD9289232051 FOREIGN KEY (addressstacked) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD92B8BA99B4 FOREIGN KEY (addresstabular) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_C0F9FD9289232051 ON admindemo_domain_model_inline (addressstacked)");
		$this->addSql("CREATE INDEX IDX_C0F9FD92B8BA99B4 ON admindemo_domain_model_inline (addresstabular)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admindemo_domain_model_inline_addressesstacked_join");
		$this->addSql("DROP TABLE admindemo_domain_model_inline_addressestabular_join");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline DROP FOREIGN KEY FK_C0F9FD9289232051");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline DROP FOREIGN KEY FK_C0F9FD92B8BA99B4");
		$this->addSql("DROP INDEX IDX_C0F9FD9289232051 ON admindemo_domain_model_inline");
		$this->addSql("DROP INDEX IDX_C0F9FD92B8BA99B4 ON admindemo_domain_model_inline");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD info VARCHAR(40) DEFAULT NULL, ADD address VARCHAR(40) DEFAULT NULL, DROP addressstacked, DROP addresstabular");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD92CB893157 FOREIGN KEY (info) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD92D4E6F81 FOREIGN KEY (address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_C0F9FD92D4E6F81 ON admindemo_domain_model_inline (address)");
		$this->addSql("CREATE INDEX IDX_C0F9FD92CB893157 ON admindemo_domain_model_inline (info)");
	}
}

?>