<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111112151403 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admindemo_domain_model_address ADD company VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_address ADD CONSTRAINT FK_301E68F64FBF094F FOREIGN KEY (company) REFERENCES admindemo_domain_model_company(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_301E68F64FBF094F ON admindemo_domain_model_address (company)");
		$this->addSql("ALTER TABLE admindemo_domain_model_company ADD notes VARCHAR(40) DEFAULT NULL, ADD addresses VARCHAR(40) DEFAULT NULL, ADD name VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_company ADD CONSTRAINT FK_72EF0E3811BA68C FOREIGN KEY (notes) REFERENCES admindemo_domain_model_note(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_company ADD CONSTRAINT FK_72EF0E386FCA7516 FOREIGN KEY (addresses) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_company ADD CONSTRAINT FK_72EF0E3821E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("CREATE INDEX IDX_72EF0E3811BA68C ON admindemo_domain_model_company (notes)");
		$this->addSql("CREATE INDEX IDX_72EF0E386FCA7516 ON admindemo_domain_model_company (addresses)");
		$this->addSql("ALTER TABLE admindemo_domain_model_note ADD company VARCHAR(40) DEFAULT NULL, ADD content VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_note ADD CONSTRAINT FK_8A8D94954FBF094F FOREIGN KEY (company) REFERENCES admindemo_domain_model_company(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_8A8D94954FBF094F ON admindemo_domain_model_note (company)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admindemo_domain_model_address DROP FOREIGN KEY FK_301E68F64FBF094F");
		$this->addSql("DROP INDEX IDX_301E68F64FBF094F ON admindemo_domain_model_address");
		$this->addSql("ALTER TABLE admindemo_domain_model_address DROP company");
		$this->addSql("ALTER TABLE admindemo_domain_model_company DROP FOREIGN KEY FK_72EF0E3811BA68C");
		$this->addSql("ALTER TABLE admindemo_domain_model_company DROP FOREIGN KEY FK_72EF0E386FCA7516");
		$this->addSql("ALTER TABLE admindemo_domain_model_company DROP FOREIGN KEY FK_72EF0E3821E3D446");
		$this->addSql("DROP INDEX IDX_72EF0E3811BA68C ON admindemo_domain_model_company");
		$this->addSql("DROP INDEX IDX_72EF0E386FCA7516 ON admindemo_domain_model_company");
		$this->addSql("ALTER TABLE admindemo_domain_model_company DROP notes, DROP addresses, DROP name");
		$this->addSql("ALTER TABLE admindemo_domain_model_note DROP FOREIGN KEY FK_8A8D94954FBF094F");
		$this->addSql("DROP INDEX IDX_8A8D94954FBF094F ON admindemo_domain_model_note");
		$this->addSql("ALTER TABLE admindemo_domain_model_note DROP company, DROP content");
	}
}

?>