<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111117171559 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admindemo_domain_model_widgets_tags_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_widgets_tags_join (admindemo_widgets VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_7E475B1199544BF5 (admindemo_widgets), INDEX IDX_7E475B11942C0B5 (admindemo_address), PRIMARY KEY(admindemo_widgets, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_tags_join ADD CONSTRAINT FK_7E475B11942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_tags_join ADD CONSTRAINT FK_7E475B1199544BF5 FOREIGN KEY (admindemo_widgets) REFERENCES admindemo_domain_model_widgets(flow3_persistence_identifier)");
	}
}

?>