<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111114042102 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_editors (flow3_persistence_identifier VARCHAR(40) NOT NULL, fullrte VARCHAR(255) DEFAULT NULL, markdown VARCHAR(255) DEFAULT NULL, textile VARCHAR(255) DEFAULT NULL, bbcode VARCHAR(255) DEFAULT NULL, wiki VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_validation (flow3_persistence_identifier VARCHAR(40) NOT NULL, required VARCHAR(255) DEFAULT NULL, string VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, stringlength VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_widgets (flow3_persistence_identifier VARCHAR(40) NOT NULL, resource VARCHAR(40) DEFAULT NULL, tag VARCHAR(40) DEFAULT NULL, info VARCHAR(40) DEFAULT NULL, string VARCHAR(255) DEFAULT NULL, boolean TINYINT(1) DEFAULT NULL, datetime DATETIME DEFAULT NULL, textarea VARCHAR(255) DEFAULT NULL, fullrte VARCHAR(255) DEFAULT NULL, markdown VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_A008E3B6BC91F416 (resource), INDEX IDX_A008E3B6389B783 (tag), INDEX IDX_A008E3B6CB893157 (info), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_widgets_tags_join (admindemo_widgets VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_7E475B1199544BF5 (admindemo_widgets), INDEX IDX_7E475B11942C0B5 (admindemo_address), PRIMARY KEY(admindemo_widgets, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_editors ADD CONSTRAINT FK_D26631F21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_validation ADD CONSTRAINT FK_6338E2B521E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B6BC91F416 FOREIGN KEY (resource) REFERENCES typo3_flow3_resource_resource(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B6389B783 FOREIGN KEY (tag) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B6CB893157 FOREIGN KEY (info) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B621E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_tags_join ADD CONSTRAINT FK_7E475B1199544BF5 FOREIGN KEY (admindemo_widgets) REFERENCES admindemo_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_tags_join ADD CONSTRAINT FK_7E475B11942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_tags_join DROP FOREIGN KEY FK_7E475B1199544BF5");
		$this->addSql("DROP TABLE admindemo_domain_model_editors");
		$this->addSql("DROP TABLE admindemo_domain_model_validation");
		$this->addSql("DROP TABLE admindemo_domain_model_widgets");
		$this->addSql("DROP TABLE admindemo_domain_model_widgets_tags_join");
	}
}

?>