<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111118120243 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_inline (flow3_persistence_identifier VARCHAR(40) NOT NULL, address VARCHAR(40) DEFAULT NULL, info VARCHAR(40) DEFAULT NULL, INDEX IDX_C0F9FD92D4E6F81 (address), INDEX IDX_C0F9FD92CB893157 (info), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_inline_addresses_join (admindemo_inline VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_D50BDAC39FE27C71 (admindemo_inline), INDEX IDX_D50BDAC3942C0B5 (admindemo_address), PRIMARY KEY(admindemo_inline, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD92D4E6F81 FOREIGN KEY (address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD92CB893157 FOREIGN KEY (info) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD9221E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline_addresses_join ADD CONSTRAINT FK_D50BDAC39FE27C71 FOREIGN KEY (admindemo_inline) REFERENCES admindemo_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline_addresses_join ADD CONSTRAINT FK_D50BDAC3942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admindemo_domain_model_inline_addresses_join DROP FOREIGN KEY FK_D50BDAC39FE27C71");
		$this->addSql("DROP TABLE admindemo_domain_model_inline");
		$this->addSql("DROP TABLE admindemo_domain_model_inline_addresses_join");
	}
}

?>