<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111201225256 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_comment (flow3_persistence_identifier VARCHAR(40) NOT NULL, content VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_event (flow3_persistence_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) DEFAULT NULL, startdate DATETIME DEFAULT NULL, enddate DATETIME DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_event_persons_join (admindemo_event VARCHAR(40) NOT NULL, admindemo_person VARCHAR(40) NOT NULL, INDEX IDX_1D502365BF5D6246 (admindemo_event), INDEX IDX_1D502365E355F0F0 (admindemo_person), PRIMARY KEY(admindemo_event, admindemo_person)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_message_receipients_join (admindemo_message VARCHAR(40) NOT NULL, admindemo_person VARCHAR(40) NOT NULL, INDEX IDX_CA21F82BB2B19F4B (admindemo_message), INDEX IDX_CA21F82BE355F0F0 (admindemo_person), PRIMARY KEY(admindemo_message, admindemo_person)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_person (flow3_persistence_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, INDEX IDX_BC4E71138D93D649 (user), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_person_electronicaddresses_join (admindemo_person VARCHAR(40) NOT NULL, party_electronicaddress VARCHAR(40) NOT NULL, INDEX IDX_96F80DD6E355F0F0 (admindemo_person), INDEX IDX_96F80DD6B06BD60D (party_electronicaddress), PRIMARY KEY(admindemo_person, party_electronicaddress)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_project_persons_join (admindemo_project VARCHAR(40) NOT NULL, admindemo_person VARCHAR(40) NOT NULL, INDEX IDX_D517D1D92BBF7FDA (admindemo_project), INDEX IDX_D517D1D9E355F0F0 (admindemo_person), PRIMARY KEY(admindemo_project, admindemo_person)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_project_tasks_join (admindemo_project VARCHAR(40) NOT NULL, admindemo_task VARCHAR(40) NOT NULL, INDEX IDX_837756402BBF7FDA (admindemo_project), INDEX IDX_837756401F57E436 (admindemo_task), PRIMARY KEY(admindemo_project, admindemo_task)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_task (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_variants (flow3_persistence_identifier VARCHAR(40) NOT NULL, resource VARCHAR(40) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, startdate DATETIME DEFAULT NULL, enddate DATETIME DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_7DC4E779BC91F416 (resource), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_widgets_addresseschosen_join (admindemo_widgets VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_5F206BD099544BF5 (admindemo_widgets), INDEX IDX_5F206BD0942C0B5 (admindemo_address), PRIMARY KEY(admindemo_widgets, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_comment ADD CONSTRAINT FK_A924551B21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_event ADD CONSTRAINT FK_A154897F21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_event_persons_join ADD CONSTRAINT FK_1D502365BF5D6246 FOREIGN KEY (admindemo_event) REFERENCES admindemo_domain_model_event(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_event_persons_join ADD CONSTRAINT FK_1D502365E355F0F0 FOREIGN KEY (admindemo_person) REFERENCES admindemo_domain_model_person(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_message_receipients_join ADD CONSTRAINT FK_CA21F82BB2B19F4B FOREIGN KEY (admindemo_message) REFERENCES admindemo_domain_model_message(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_message_receipients_join ADD CONSTRAINT FK_CA21F82BE355F0F0 FOREIGN KEY (admindemo_person) REFERENCES admindemo_domain_model_person(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_person ADD CONSTRAINT FK_BC4E71138D93D649 FOREIGN KEY (user) REFERENCES admin_security_user(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_person ADD CONSTRAINT FK_BC4E711321E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_person_electronicaddresses_join ADD CONSTRAINT FK_96F80DD6E355F0F0 FOREIGN KEY (admindemo_person) REFERENCES admindemo_domain_model_person(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_person_electronicaddresses_join ADD CONSTRAINT FK_96F80DD6B06BD60D FOREIGN KEY (party_electronicaddress) REFERENCES typo3_party_domain_model_electronicaddress(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_persons_join ADD CONSTRAINT FK_D517D1D92BBF7FDA FOREIGN KEY (admindemo_project) REFERENCES admindemo_domain_model_project(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_persons_join ADD CONSTRAINT FK_D517D1D9E355F0F0 FOREIGN KEY (admindemo_person) REFERENCES admindemo_domain_model_person(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_tasks_join ADD CONSTRAINT FK_837756402BBF7FDA FOREIGN KEY (admindemo_project) REFERENCES admindemo_domain_model_project(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_tasks_join ADD CONSTRAINT FK_837756401F57E436 FOREIGN KEY (admindemo_task) REFERENCES admindemo_domain_model_task(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_task ADD CONSTRAINT FK_174EB5A421E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_variants ADD CONSTRAINT FK_7DC4E779BC91F416 FOREIGN KEY (resource) REFERENCES typo3_flow3_resource_resource(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_variants ADD CONSTRAINT FK_7DC4E77921E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_addresseschosen_join ADD CONSTRAINT FK_5F206BD099544BF5 FOREIGN KEY (admindemo_widgets) REFERENCES admindemo_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_addresseschosen_join ADD CONSTRAINT FK_5F206BD0942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_address DROP FOREIGN KEY FK_301E68F621E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_address ADD CONSTRAINT FK_301E68F621E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations DROP FOREIGN KEY FK_59E787E021E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations ADD CONSTRAINT FK_59E787E021E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_editors DROP FOREIGN KEY FK_D26631F21E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_editors ADD CONSTRAINT FK_D26631F21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline DROP FOREIGN KEY FK_C0F9FD9221E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD9221E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_message DROP FOREIGN KEY FK_8BED370821E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_message ADD CONSTRAINT FK_8BED37085F004ACF FOREIGN KEY (sender) REFERENCES admindemo_domain_model_person(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_message ADD CONSTRAINT FK_8BED370821E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_project DROP FOREIGN KEY FK_12E3D79921E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_project ADD CONSTRAINT FK_12E3D79921E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_validation DROP FOREIGN KEY FK_6338E2B521E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_validation DROP string");
		$this->addSql("ALTER TABLE admindemo_domain_model_validation ADD CONSTRAINT FK_6338E2B521E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets DROP FOREIGN KEY FK_A008E3B621E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B621E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admindemo_domain_model_event_persons_join DROP FOREIGN KEY FK_1D502365BF5D6246");
		$this->addSql("ALTER TABLE admindemo_domain_model_event_persons_join DROP FOREIGN KEY FK_1D502365E355F0F0");
		$this->addSql("ALTER TABLE admindemo_domain_model_message DROP FOREIGN KEY FK_8BED37085F004ACF");
		$this->addSql("ALTER TABLE admindemo_domain_model_message_receipients_join DROP FOREIGN KEY FK_CA21F82BE355F0F0");
		$this->addSql("ALTER TABLE admindemo_domain_model_person_electronicaddresses_join DROP FOREIGN KEY FK_96F80DD6E355F0F0");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_persons_join DROP FOREIGN KEY FK_D517D1D9E355F0F0");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_tasks_join DROP FOREIGN KEY FK_837756401F57E436");
		$this->addSql("DROP TABLE admindemo_domain_model_comment");
		$this->addSql("DROP TABLE admindemo_domain_model_event");
		$this->addSql("DROP TABLE admindemo_domain_model_event_persons_join");
		$this->addSql("DROP TABLE admindemo_domain_model_message_receipients_join");
		$this->addSql("DROP TABLE admindemo_domain_model_person");
		$this->addSql("DROP TABLE admindemo_domain_model_person_electronicaddresses_join");
		$this->addSql("DROP TABLE admindemo_domain_model_project_persons_join");
		$this->addSql("DROP TABLE admindemo_domain_model_project_tasks_join");
		$this->addSql("DROP TABLE admindemo_domain_model_task");
		$this->addSql("DROP TABLE admindemo_domain_model_variants");
		$this->addSql("DROP TABLE admindemo_domain_model_widgets_addresseschosen_join");
		$this->addSql("ALTER TABLE admindemo_domain_model_address DROP FOREIGN KEY FK_301E68F621E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_address ADD CONSTRAINT FK_301E68F621E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations DROP FOREIGN KEY FK_59E787E021E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations ADD CONSTRAINT FK_59E787E021E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_editors DROP FOREIGN KEY FK_D26631F21E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_editors ADD CONSTRAINT FK_D26631F21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline DROP FOREIGN KEY FK_C0F9FD9221E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_inline ADD CONSTRAINT FK_C0F9FD9221E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_message DROP FOREIGN KEY FK_8BED37085F004ACF");
		$this->addSql("ALTER TABLE admindemo_domain_model_message DROP FOREIGN KEY FK_8BED370821E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_message ADD CONSTRAINT FK_8BED370821E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_project DROP FOREIGN KEY FK_12E3D79921E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_project ADD CONSTRAINT FK_12E3D79921E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_validation DROP FOREIGN KEY FK_6338E2B521E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_validation ADD string VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_validation ADD CONSTRAINT FK_6338E2B521E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets DROP FOREIGN KEY FK_A008E3B621E3D446");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B621E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier)");
	}
}

?>