<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111117171529 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_todo_projects_join (admindemo_todo VARCHAR(40) NOT NULL, admindemo_project VARCHAR(40) NOT NULL, INDEX IDX_DAB1A983172789B3 (admindemo_todo), INDEX IDX_DAB1A9832BBF7FDA (admindemo_project), PRIMARY KEY(admindemo_todo, admindemo_project)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_widgets_addresses_join (admindemo_widgets VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_95C104CC99544BF5 (admindemo_widgets), INDEX IDX_95C104CC942C0B5 (admindemo_address), PRIMARY KEY(admindemo_widgets, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_todo_projects_join ADD CONSTRAINT FK_DAB1A983172789B3 FOREIGN KEY (admindemo_todo) REFERENCES admindemo_domain_model_todo(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_todo_projects_join ADD CONSTRAINT FK_DAB1A9832BBF7FDA FOREIGN KEY (admindemo_project) REFERENCES admindemo_domain_model_project(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_addresses_join ADD CONSTRAINT FK_95C104CC99544BF5 FOREIGN KEY (admindemo_widgets) REFERENCES admindemo_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets_addresses_join ADD CONSTRAINT FK_95C104CC942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_todo ADD name VARCHAR(255) DEFAULT NULL, ADD description VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets DROP FOREIGN KEY FK_A008E3B6389B783");
		$this->addSql("DROP INDEX IDX_A008E3B6389B783 ON admindemo_domain_model_widgets");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets CHANGE tag address VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B6D4E6F81 FOREIGN KEY (address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_A008E3B6D4E6F81 ON admindemo_domain_model_widgets (address)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admindemo_domain_model_todo_projects_join");
		$this->addSql("DROP TABLE admindemo_domain_model_widgets_addresses_join");
		$this->addSql("ALTER TABLE admindemo_domain_model_todo DROP name, DROP description");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets DROP FOREIGN KEY FK_A008E3B6D4E6F81");
		$this->addSql("DROP INDEX IDX_A008E3B6D4E6F81 ON admindemo_domain_model_widgets");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets CHANGE address tag VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_widgets ADD CONSTRAINT FK_A008E3B6389B783 FOREIGN KEY (tag) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_A008E3B6389B783 ON admindemo_domain_model_widgets (tag)");
	}
}

?>