<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111114044400 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_project_users_join (admindemo_project VARCHAR(40) NOT NULL, security_security_user VARCHAR(40) NOT NULL, INDEX IDX_A611B6382BBF7FDA (admindemo_project), INDEX IDX_A611B638DB6BE496 (security_security_user), PRIMARY KEY(admindemo_project, security_security_user)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_users_join ADD CONSTRAINT FK_A611B6382BBF7FDA FOREIGN KEY (admindemo_project) REFERENCES admindemo_domain_model_project(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_project_users_join ADD CONSTRAINT FK_A611B638DB6BE496 FOREIGN KEY (security_security_user) REFERENCES admin_security_user(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admindemo_domain_model_project_users_join");
	}
}

?>