<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111118160017 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admindemo_domain_model_annotations_addressesstacked_join (admindemo_annotations VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_ECF47F774E26E6BB (admindemo_annotations), INDEX IDX_ECF47F77942C0B5 (admindemo_address), PRIMARY KEY(admindemo_annotations, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admindemo_domain_model_annotations_addressestabular_join (admindemo_annotations VARCHAR(40) NOT NULL, admindemo_address VARCHAR(40) NOT NULL, INDEX IDX_5825B2054E26E6BB (admindemo_annotations), INDEX IDX_5825B205942C0B5 (admindemo_address), PRIMARY KEY(admindemo_annotations, admindemo_address)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations_addressesstacked_join ADD CONSTRAINT FK_ECF47F774E26E6BB FOREIGN KEY (admindemo_annotations) REFERENCES admindemo_domain_model_annotations(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations_addressesstacked_join ADD CONSTRAINT FK_ECF47F77942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations_addressestabular_join ADD CONSTRAINT FK_5825B2054E26E6BB FOREIGN KEY (admindemo_annotations) REFERENCES admindemo_domain_model_annotations(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations_addressestabular_join ADD CONSTRAINT FK_5825B205942C0B5 FOREIGN KEY (admindemo_address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations ADD address VARCHAR(40) DEFAULT NULL, ADD addresses VARCHAR(40) DEFAULT NULL, ADD addressstacked VARCHAR(40) DEFAULT NULL, ADD addresstabular VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations ADD CONSTRAINT FK_59E787E0D4E6F81 FOREIGN KEY (address) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations ADD CONSTRAINT FK_59E787E06FCA7516 FOREIGN KEY (addresses) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations ADD CONSTRAINT FK_59E787E089232051 FOREIGN KEY (addressstacked) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations ADD CONSTRAINT FK_59E787E0B8BA99B4 FOREIGN KEY (addresstabular) REFERENCES admindemo_domain_model_address(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_59E787E0D4E6F81 ON admindemo_domain_model_annotations (address)");
		$this->addSql("CREATE INDEX IDX_59E787E06FCA7516 ON admindemo_domain_model_annotations (addresses)");
		$this->addSql("CREATE INDEX IDX_59E787E089232051 ON admindemo_domain_model_annotations (addressstacked)");
		$this->addSql("CREATE INDEX IDX_59E787E0B8BA99B4 ON admindemo_domain_model_annotations (addresstabular)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admindemo_domain_model_annotations_addressesstacked_join");
		$this->addSql("DROP TABLE admindemo_domain_model_annotations_addressestabular_join");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations DROP FOREIGN KEY FK_59E787E0D4E6F81");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations DROP FOREIGN KEY FK_59E787E06FCA7516");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations DROP FOREIGN KEY FK_59E787E089232051");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations DROP FOREIGN KEY FK_59E787E0B8BA99B4");
		$this->addSql("DROP INDEX IDX_59E787E0D4E6F81 ON admindemo_domain_model_annotations");
		$this->addSql("DROP INDEX IDX_59E787E06FCA7516 ON admindemo_domain_model_annotations");
		$this->addSql("DROP INDEX IDX_59E787E089232051 ON admindemo_domain_model_annotations");
		$this->addSql("DROP INDEX IDX_59E787E0B8BA99B4 ON admindemo_domain_model_annotations");
		$this->addSql("ALTER TABLE admindemo_domain_model_annotations DROP address, DROP addresses, DROP addressstacked, DROP addresstabular");
	}
}

?>